spring.application.name=EmployeeTransportProblem
server.port=5353
spring.datasource.url=jdbc:mysql://localhost:3306/employee_transport
spring.datasource.username=root
spring.datasource.password=1234



